"""Export every slide of both comparison decks to PNG, exactly as PowerPoint renders them.

Windows + Microsoft PowerPoint only. Run this locally whenever a source deck
changes, then commit the regenerated images under slide_images/.

pptx/driftwood_...pptx is a straight copy of the original source deck.
pptx/cheniere_sabine_pass_...pptx is generated by build_sabine_deck.py (run
that script first if you've changed its content) — it is authored from
scratch in the same visual format as the Driftwood deck, because the
original Sabine Pass source file's native <a:tbl> tables are encoded in a
way real PowerPoint refuses to open, even though python-pptx/LibreOffice
read it fine.

pptx/cheniere_followon_gdf_...pptx is generated by build_followon_deck.py in
the same visual format (BG Gulf Coast A&R, Centrica, GNF Corpus Christi,
Woodside, GdF Master Ex-Ship).

Usage:
    python scripts/build_sabine_deck.py     # only if Sabine content changed
    python scripts/build_followon_deck.py   # only if follow-on content changed
    python scripts/export_slides.py
"""

import time
from pathlib import Path

import win32com.client

ROOT = Path(__file__).parent.parent
SLIDE_IMAGES_DIR = ROOT / "slide_images"
PPTX_DIR = ROOT / "pptx"

DRIFTWOOD_SRC = ROOT / "driftwood_lng_spa_economic_terms_comparison_formula_signature_updated.pptx"

DECKS = {
    "driftwood": DRIFTWOOD_SRC.name,
    "sabine_pass": "cheniere_sabine_pass_spa_standalone_economic_terms.pptx",
    "followon_gdf": "cheniere_followon_gdf_spa_economic_terms.pptx",
}

EXPORT_WIDTH = 1600
EXPORT_HEIGHT = 900


def export_deck(app, key: str, pptx_path: Path):
    out_dir = SLIDE_IMAGES_DIR / key
    out_dir.mkdir(parents=True, exist_ok=True)
    for old in out_dir.glob("slide-*.png"):
        old.unlink()

    presentation = app.Presentations.Open(str(pptx_path), WithWindow=False)
    try:
        count = presentation.Slides.Count
        for i in range(1, count + 1):
            out_path = out_dir / f"slide-{i:02d}.png"
            presentation.Slides.Item(i).Export(str(out_path), "PNG", EXPORT_WIDTH, EXPORT_HEIGHT)
        print(f"{key}: exported {count} slides -> {out_dir}")
    finally:
        presentation.Close()


def main():
    PPTX_DIR.mkdir(exist_ok=True)
    driftwood_out = PPTX_DIR / DRIFTWOOD_SRC.name
    driftwood_out.write_bytes(DRIFTWOOD_SRC.read_bytes())

    app = win32com.client.DispatchEx("PowerPoint.Application")
    try:
        for key, filename in DECKS.items():
            export_deck(app, key, PPTX_DIR / filename)
    finally:
        time.sleep(1)
        app.Quit()


if __name__ == "__main__":
    main()
